version: "3.7"

networks:
  net:
    driver: overlay
    attachable: true

volumes:
    prometheus:
    grafana:
    alertmanager:

configs:
  node_rules:
    file: ./prometheus/rules/swarm_node.rules.yml
  task_rules:
    file: ./prometheus/rules/swarm_task.rules.yml
  prom-config:
    file: ./prometheus/conf/prometheus.yml
  grafana-datasources:
    file: ./grafana/datasources/prometheus.yml
  grafana-dashboards:
    file: ./grafana/dashboards.yml

services:
  cadvisor:
    image: google/cadvisor
    networks:
      - net
    command: -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/dashboards/:/etc/grafana/dashboards
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards-src.yml
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources/
    configs:
      - source: grafana-datasources
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana-dashboards
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
    depends_on:
      - prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    networks:
      - net
    volumes:
      - alertmanager:/alertmanager
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  node-exporter:
    image: prom/node-exporter
    networks:
      - net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/node-meta.prom:/etc/node-exporter/node-meta.prom
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - net
    volumes:
      - prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
      - source: prom-config
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 128M
