version: "3.7"

networks:
  net:
    driver: overlay
    attachable: true

volumes:
    prometheus:
      driver: rbd
    grafana:
      driver: rbd
    alertmanager:
      driver: rbd
    grafana_conf:
      driver: cephfs

configs:
  node_rules:
    file: ./prometheus/rules/swarm_node.rules.yml
  task_rules:
    file: ./prometheus/rules/swarm_task.rules.yml
  prom-config:
    file: ./prometheus/conf/prometheus.yml
  grafana-datasources:
    file: ./grafana/datasources/prometheus.yml
  grafana-dashboards:
    file: ./grafana/dashboards.yml
  node_exprt:
    file: ./node-exporter/node-meta.prom

services:
  cadvisor:
    image: google/cadvisor
    networks:
      - net
    command: -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana:/var/lib/grafana
      - grafana_conf:/etc/grafana
    configs:
      - source: grafana-datasources
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana-dashboards
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
    depends_on:
      - prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    networks:
      - net
    volumes:
      - alertmanager:/alertmanager
    deploy:
      placement:
        constraints:
          - node.role == manager

  node-exporter:
    image: prom/node-exporter
    networks:
      - net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /home/vagrant/node-meta.prom:/etc/node-exporter/node-meta.prom
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - net
    volumes:
      - prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
      - source: prom-config
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
